/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface YoobicBasicGrid {
        "array": any[];
        "display_key": string;
    }
}
declare global {
    interface HTMLYoobicBasicGridElement extends Components.YoobicBasicGrid, HTMLStencilElement {
    }
    var HTMLYoobicBasicGridElement: {
        prototype: HTMLYoobicBasicGridElement;
        new (): HTMLYoobicBasicGridElement;
    };
    interface HTMLElementTagNameMap {
        "yoobic-basic-grid": HTMLYoobicBasicGridElement;
    }
}
declare namespace LocalJSX {
    interface YoobicBasicGrid {
        "array"?: any[];
        "display_key"?: string;
    }
    interface IntrinsicElements {
        "yoobic-basic-grid": YoobicBasicGrid;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "yoobic-basic-grid": LocalJSX.YoobicBasicGrid & JSXBase.HTMLAttributes<HTMLYoobicBasicGridElement>;
        }
    }
}
